/** Publication results are computed once in Python; the browser never refits the study. */
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt = (value, digits = 3) => value.toLocaleString('en-US', {maximumFractionDigits: digits});
const fixed = (value, digits = 4) => value.toFixed(digits);
let snapshot, requestNumber = 0;

function ratioChart(row, convention) {
  const width = 660, left = 150, right = 35, max = Math.max(1.1, row.paper_code.upper * 1.12);
  const x = value => left + value / max * (width - left - right);
  let chart = `<svg viewBox="0 0 ${width} 190" role="img" aria-label="Rate ratio under the paper-code and Equation 2 interval conventions. A ratio of 1 means equal rates."><title>Waymo to human rate ratio: ${fixed(row.paper_code.ratio)}. Paper-code interval ${fixed(row.paper_code.lower)}–${fixed(row.paper_code.upper)}; Equation 2 interval ${fixed(row.equation.lower)}–${fixed(row.equation.upper)}.</title>`;
  for (const value of [0, .25, .5, .75, 1]) chart += `<line x1="${x(value)}" x2="${x(value)}" y1="23" y2="133" stroke="${value === 1 ? '#a56943' : '#e0e6de'}" stroke-dasharray="${value === 1 ? '4 4' : ''}"/><text x="${x(value)}" y="155" text-anchor="middle" fill="#53665a" font-size="10">${value}</text>`;
  [['paper_code','Paper-code tails',55,'#af6941'],['equation','Equation 2 · 95%',108,'#087d68']].forEach(([key,label,y,color]) => {
    const result = row[key];
    chart += `<text x="${left-18}" y="${y+4}" text-anchor="end" fill="#364e43" font-size="11">${label}</text><line x1="${x(result.lower)}" x2="${x(result.upper)}" y1="${y}" y2="${y}" stroke="${color}" stroke-width="${convention === key ? 5 : 2}"/><path d="M${x(result.lower)},${y-7}v14M${x(result.upper)},${y-7}v14" stroke="${color}"/><circle cx="${x(result.ratio)}" cy="${y}" r="6" fill="${color}" stroke="white" stroke-width="2"/>`;
  });
  return chart + `<text x="${left}" y="180" fill="#53665a" font-size="9">LOWER WAYMO RATE ←</text><text x="${x(1)}" y="180" text-anchor="middle" fill="#8a5232" font-size="9">EQUAL RATES</text></svg>`;
}

function renderStudy(study, state) {
  const row = study.comparisons.find(r => r.id === state.comparison) || study.comparisons[0];
  const convention = state.convention === 'equation' ? 'equation' : 'paper_code';
  const result = row[convention], paper = convention === 'paper_code';
  const outside = result.upper < 1;
  const cohort = row.cohort;
  const title = paper ? 'Published-code reproduction' : 'Equation 2 · conventional 95%';
  const description = paper ? '1.25% in each tail · 97.5% central probability in the model' : '2.5% in each tail · 95% central probability in the model';
  return `<div class="study-masthead"><div class="eyebrow"><span class="status-dot"></span> REPRODUCTION NOTE 001 <span class="study-separator">/</span> HISTORICAL STUDY</div><h1>From a published claim<br>to <em>checkable evidence.</em></h1><p>Recount the events. Rebuild the estimate. Inspect the differences.<br>A transparent reproduction of four comparisons in Waymo’s 7.1-million-mile paper.</p><div class="study-meta"><span>Rider-only crashes</span><span>Through October 2023</span><span>Frozen paper · v3</span></div><div class="study-seal"><strong>${study.audit.checks_passed}<span> / ${study.audit.checks_total}</span></strong><span>reference checks match</span><small>Counts exact · ratio tolerance &lt; 0.01</small></div></div>
  <nav class="study-jump" aria-label="Study sections"><a href="#study-result">01 Result</a><a href="#study-audit">02 Reproduction audit</a><a href="#study-cohort">03 Event trail</a><a href="#study-sources">04 Sources & limits</a></nav>
  <div class="study-controls"><div><label for="study-comparison">PUBLISHED COMPARISON</label><select id="study-comparison">${study.comparisons.map(r => `<option value="${r.id}" ${r.id===row.id?'selected':''}>${esc(r.location_label)} · ${esc(r.outcome_label)}${r.id==='sf-injury'?' · primary':''}</option>`).join('')}</select></div><div><span class="study-control-label" id="study-interval-label">INTERVAL CONVENTION</span><div class="study-toggle" role="group" aria-labelledby="study-interval-label"><button id="study-paper" data-convention="paper_code" aria-pressed="${paper}">Paper code</button><button id="study-equation" data-convention="equation" aria-pressed="${!paper}">Equation 2 · 95%</button></div></div></div>
  <div class="study-result-grid" id="study-result"><article class="study-result-card"><span class="eyebrow">${esc(row.location_label.toUpperCase())} / ${esc(row.outcome_label.toUpperCase())}</span><div class="study-headline">${fmt(row.reduction_percent,1)}<span>%</span></div><h2>lower observed crashed-vehicle rate</h2><p>Relative to the paper’s ${row.outcome==='any_injury'?'Blincoe-adjusted injury':'police-reported'} human benchmark, using the published mileage.</p><div class="study-result-details"><div><span>Recalculated rate ratio</span><strong>${fixed(result.ratio)}</strong></div><div><span>Selected interval</span><strong>${fixed(result.lower)}–${fixed(result.upper)}</strong></div></div><p class="study-interval-note">${title}<br>${description}</p><div class="study-conclusion">${outside?'This interval excludes equal rates.':'This interval includes equal rates; the observed reduction is uncertain.'} This historical association does not establish a causal effect or current fleet performance.</div></article>
  <article class="card study-evidence-card"><div class="card-title"><h2>The denominator comes first.</h2><span class="mini-badge">PER MILLION MILES</span></div><div class="study-evidence-row"><div><span class="study-series"><i></i>Waymo rider-only</span><strong>${fixed(row.waymo_ipmm,3)}</strong><small>${row.events} ${row.events===1?'event':'events'} / ${fmt(row.waymo_miles,0)} miles</small></div><div class="study-evidence-bar"><span style="width:${row.waymo_ipmm/row.benchmark_ipmm*100}%"></span></div></div><div class="study-evidence-row human"><div><span class="study-series"><i></i>Human benchmark</span><strong>${fixed(row.benchmark_ipmm,2)}</strong><small>Published ${row.outcome==='any_injury'?'adjusted':'observed'} rate · Table 2</small></div><div class="study-evidence-bar"><span style="width:100%"></span></div></div><div class="study-expectation"><strong>${fmt(row.expected_at_benchmark,2)}</strong><p>expected events at the benchmark rate over the same ${fmt(row.waymo_miles/1e6,3)} million miles.<br><b>${row.events} ${row.events===1?'was':'were'} observed.</b> Expected events are a calculation, not an observed control group.</p></div><p class="caption">Waymo rate: ${fixed(row.waymo_ipmm,3)} [${fixed(row.rate_lower,3)}, ${fixed(row.rate_upper,3)}] per million miles, two-sided 95% Garwood interval. The benchmark’s exposure is ${fmt(row.benchmark_miles/1e6,0)} million human miles; it is not the Waymo denominator.</p></article></div>
  <article class="card study-uncertainty"><div><span class="method-number">ONE ESTIMATE, TWO INTERVAL CONVENTIONS</span><h2>A detail worth reproducing.</h2><p>The paper’s Equation 2 uses 2.5% tails at α = 0.05. Appendix A.3 first halves α for positive counts, then halves it again: 1.25% tails. The code therefore produces a wider interval.</p><p>We preserve that code to reproduce Table 7, and show the equation separately. The source calls its intervals 95%; the code’s central probability is 97.5% for these positive-count cases. This describes the model calculation, not guaranteed coverage for adjusted benchmarks.</p><a href="${study.paper_url}#page=22" target="_blank" rel="noopener">Inspect Appendix A.3 ↗</a></div><div class="study-ratio-chart">${ratioChart(row, convention)}<p class="caption">Same counts, miles and point estimate. Only the tail convention changes.${row.id==='phx-injury'?' In Phoenix’s injury comparison, this changes whether the interval includes 1.':''}</p></div></article>
  <section id="study-audit" class="study-section"><div class="section-heading"><div><h2><span class="section-index">02</span>Published vs. reproduced</h2><p>Audit targets come from Table 7. Calculations use counts and exposure, not the targets.</p></div><span class="pill">${row.checks.filter(c=>c.matches).length} / ${row.checks.length} matched</span></div><div class="card data-card"><div class="table-wrap"><table id="study-audit-table"><caption class="sr-only">Reproduction audit for ${esc(row.location_label)}, ${esc(row.outcome_label)}</caption><thead><tr><th scope="col">Quantity</th><th scope="col">Published</th><th scope="col">Reproduced</th><th scope="col">Difference</th><th scope="col">Audit</th></tr></thead><tbody>${row.checks.map(c=>`<tr><th scope="row">${c.quantity}</th><td>${fmt(c.published,3)}</td><td>${c.quantity==='Included events'?c.reproduced:fixed(c.reproduced,6)}</td><td>${c.delta===0?'0':`${c.delta>0?'+':''}${fixed(c.delta,6)}`}</td><td><span class="study-match">${c.matches?'✓ Match':'Review'}</span></td></tr>`).join('')}</tbody></table></div><p class="study-table-note">Ratios and limits use <strong>paper-code tails</strong> here, regardless of the display toggle. Counts must match exactly. Absolute ratio/endpoint tolerance &lt; 0.01 follows Appendix A.3 Listing 2. Rounded source inputs prevent a claim of bit-for-bit agreement.</p></div></section>
  <section id="study-cohort" class="study-section"><div class="section-heading"><div><h2><span class="section-index">03</span>Follow the event trail</h2><p>Every inclusion has a source row. The paper’s classifications are retained.</p></div><a class="small-button" href="/waymo-project/replication-events.csv" download>↓ All 73 event rows</a></div><div class="study-flow"><div><strong>${cohort.listed}</strong><span>listed ${esc(row.location_label)} events</span></div><span class="study-flow-arrow" aria-hidden="true">→</span><div><strong>${cohort.in_transport_impacted}</strong><span>in-transport & impacted</span><small>${cohort.excluded_transport_or_contact} excluded by that membership</small></div><span class="study-flow-arrow" aria-hidden="true">→</span><div><strong>${cohort.included}</strong><span>${esc(row.outcome_label.toLowerCase())}</span><small>${cohort.excluded_outcome} do not meet this outcome</small></div></div><div class="study-event-list"><span>INCLUDED EVENT IDENTIFIERS</span><div>${row.event_ids.map(id=>`<a href="${study.paper_url}#page=${study.events.find(e=>e.event_id===id).source_page}" target="_blank" rel="noopener">${esc(id)} ↗</a>`).join('')}</div></div><p class="caption">The full appendix contains 73 events across Phoenix, San Francisco and Los Angeles, including two pre-SGO events the authors judged reportable retrospectively. Both are retained with their original early-study identifiers. Los Angeles is retained in the source audit but is outside these four published reference cases. No newer NHTSA records or DMV testing miles are merged into this study.</p></section>
  <section id="study-sources" class="study-section"><div class="section-heading"><div><h2><span class="section-index">04</span>Run it. Inspect it. Challenge it.</h2><p>A frozen source and a repeatable calculation.</p></div></div><div class="study-source-grid"><article class="card"><span class="method-number">THE SOURCE</span><h3>Comparison of Waymo Rider-Only Crash Data to Human Benchmarks at 7.1 Million Miles</h3><p>Kusano et al. · Traffic Injury Prevention<br>Accepted manuscript, arXiv v3 · October 24, 2024</p><p class="caption">Table 2: human benchmark rates and mileage.<br>Table 7: published comparison targets.<br>Appendix A.1: all event memberships.<br>Appendix A.3: precise reference inputs and code.</p><div class="source-links"><a href="${study.paper_url}" target="_blank" rel="noopener">Frozen paper ↗</a><a href="${study.doi_url}" target="_blank" rel="noopener">Journal DOI ↗</a><a href="/waymo-project/replication-manifest.json" download>↓ Provenance & hashes</a></div></article><article class="card"><span class="method-number">REPRODUCE IN ONE COMMAND</span><h3>From the repository checkout</h3><pre class="study-command"><code>uv run --group research python \\
  scripts/reproduce_study.py --from-source</code></pre><p class="caption">Downloads the versioned paper, verifies its SHA-256, re-extracts all 73 event rows, recalculates the estimates, checks the published references, and regenerates the website data. Without <code>--from-source</code>, it runs offline on committed inputs. The four benchmark/reference rows are documented transcriptions; the PDF extractor verifies event memberships.</p><div class="source-links"><a href="/waymo-project/replication-results.csv" download>↓ All comparison checks</a><a href="/waymo-project/replication-inputs.csv" download>↓ Calculation inputs</a><a href="https://github.com/kushal-acharya/av-safety-rate-explorer/blob/main/docs/replication-study.md" target="_blank" rel="noopener">Technical note ↗</a></div></article></div><div class="study-limits"><h3>What this reproduction establishes</h3><p>The selected results can be recovered from the publication’s event memberships and rounded benchmark inputs, within its stated tolerance. This is an independent calculation using author-supplied data, not an independent validation of crash reporting, outcome adjudication, or the underlying human benchmark.</p><p>Injury benchmarks include an underreporting adjustment whose uncertainty is not propagated here. The comparisons are observational, historical and city-level; they do not establish current performance, causal effects, release readiness or a complete safety case. No spatial reweighting is claimed.</p></div></section>`;
}

export async function mountReplication(element, state) {
  const request = ++requestNumber;
  element.innerHTML = '<div class="empty-state" role="status">Loading the frozen publication study…</div>';
  try {
    if (!snapshot) snapshot = fetch('/waymo-project/replication.json').then(response => {
      if (!response.ok) throw new Error('The publication snapshot could not be loaded.');
      return response.json();
    });
    const study = await snapshot;
    if (request !== requestNumber) return;
    element.innerHTML = renderStudy(study, state);
    element.querySelector('#study-comparison').onchange = event => state.onChange({comparison: event.target.value});
    element.querySelectorAll('[data-convention]').forEach(button => button.onclick = () => state.onChange({convention: button.dataset.convention}));
  } catch (error) {
    snapshot = undefined;
    element.innerHTML = `<div class="empty-state" role="alert"><h2>Study unavailable</h2><p>${esc(error.message)}</p><button id="study-retry" class="small-button">Retry</button></div>`;
    element.querySelector('#study-retry').onclick = () => mountReplication(element, state);
  }
}
