/** End-to-end checks against a running local preview or the deployed URL. */
import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const origin=process.env.AV_TEST_ORIGIN || 'http://localhost:8789';
const browser=await chromium.launch({headless:true,channel:process.env.CI?undefined:'chrome'});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try {
  await page.goto(`${origin}/waymo-project/`,{waitUntil:'networkidle'});
  await page.locator('#rates-table').waitFor();
  assert.equal(await page.locator('#confidence').inputValue(),'0.95');
  assert.equal(await page.locator('#rates-table tbody tr').count(),5);
  assert.match(await page.locator('#view-rates').innerText(),/11.91M/);
  assert.equal(await page.locator('#context-table tbody tr').count(),5);
  await page.selectOption('#context-dimension','location');
  assert.equal(await page.locator('#context-table tbody tr').count(),7);
  assert.match(await page.locator('#event-context').innerText(),/Road|road type|road classes/);
  assert.ok(page.url().includes('context=location'));
  await page.selectOption('#context-dimension','cause_category');
  assert.match(await page.locator('#event-context').innerText(),/not validated root causes/);
  const contextDownload=page.waitForEvent('download');await page.click('#context-export');
  assert.equal((await contextDownload).suggestedFilename(),'av-evidence-event-context.csv');
  await page.reload({waitUntil:'networkidle'});
  assert.equal(await page.locator('#context-dimension').inputValue(),'cause_category');
  await page.selectOption('#context-dimension','initiated_by');
  await page.selectOption('#interval-method','poisson');
  assert.match(await page.locator('#rates-table tbody').innerText(),/0.102/);
  await page.selectOption('#confidence','0.99');
  assert.match(await page.locator('#view-rates').innerText(),/99%/);
  await page.click('[data-year="2020"]');
  assert.equal(await page.locator('#rates-table tbody tr').count(),4);
  await page.click('.nav-item[data-tab="compare"]');
  assert.match(await page.locator('#view-compare').innerText(),/Exact conditional p-value/);
  await page.selectOption('#group-b','Waymo|2024');
  assert.match(await page.locator('#view-compare').innerText(),/2024/);
  await page.click('.nav-item[data-tab="planner"]');
  await page.fill('#baseline','1');await page.locator('#baseline').blur();
  await page.fill('#phi','1');await page.locator('#phi').blur();
  assert.match(await page.locator('#planner-output').innerText(),/2.98M/);
  await page.locator('#reduction').fill('20');
  assert.doesNotMatch(await page.locator('#planner-output').innerText(),/2.98M/);
  await page.fill('#baseline','0');await page.locator('#baseline').blur();
  assert.equal(await page.locator('#planner-output [role="alert"]').count(),1);
  await page.fill('#baseline','1');await page.locator('#baseline').blur();
  await page.screenshot({path:'assets/planner.png',fullPage:true});
  await page.click('.nav-item[data-tab="methods"]');
  assert.match(await page.locator('#view-methods').innerText(),/128 \/ 128/);
  await page.click('.nav-item[data-tab="rates"]');await page.click('#reset');
  const downloadPromise=page.waitForEvent('download');await page.click('#export-csv');
  assert.equal((await downloadPromise).suggestedFilename(),'av-evidence-selection.csv');
  await page.selectOption('#mode','driverless');
  assert.equal(await page.locator('#rates-table tbody tr').count(),2);
  await page.click('#company-summary');await page.click('#clear-companies');
  assert.match(await page.locator('#view-rates').innerText(),/No exposure/);
  await page.locator('#company-options input[value="Zoox"]').check();
  assert.match(await page.locator('#rates-table tbody').innerText(),/Upper bound only/);
  assert.match(await page.locator('#event-context').innerText(),/Event shares are undefined/);
  await page.click('#company-summary');await page.click('#reset');
  await page.click('#company-summary');await page.click('#all-companies');await page.click('#company-summary');
  assert.ok(await page.locator('#rates-table tbody tr').count()>25);
  await page.click('#reset');
  await page.screenshot({path:'assets/screenshot.png',fullPage:true});
  const shareURL=page.url();await page.goto(shareURL,{waitUntil:'networkidle'});
  assert.equal(await page.locator('#rates-table tbody tr').count(),5);
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'assets/mobile.png',fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile page must not overflow horizontally');
  await page.click('.nav-item[data-tab="planner"]');
  assert.ok(await page.locator('#planner-output').isVisible());
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile planner overflow');
  assert.deepEqual(errors,[]);
  console.log('Browser checks passed: filters, intervals, comparison, planner, invalid input, zero events, download, share URL, mobile, no JS errors.');
} finally { await browser.close(); }
